"""add_daily_calorie_goal_to_users

Revision ID: 358b9f5ead8b
Revises: 3592bec0fea4
Create Date: 2026-04-19 10:22:32.933898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '358b9f5ead8b'
down_revision: Union[str, Sequence[str], None] = '3592bec0fea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_calorie_goal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_calorie_goal')
    # ### end Alembic commands ###
