"""add_budget_id_to_transactions

Revision ID: f26a9a0351a4
Revises: f8af64d64fa4
Create Date: 2026-04-19 15:45:26.542086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f26a9a0351a4'
down_revision: Union[str, Sequence[str], None] = 'f8af64d64fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('budget_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'budgets', ['budget_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'budget_id')
    # ### end Alembic commands ###
